/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml.impl;

import org.eclipse.emf.ecore.EClass;

import org.smalluml.smalluml.Date;
import org.smalluml.smalluml.SmallumlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Date</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DateImpl extends SuperTypeImpl implements Date
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmallumlPackage.Literals.DATE;
  }

} //DateImpl
