/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml.impl;

import org.eclipse.emf.ecore.EClass;

import org.smalluml.smalluml.SmallumlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringImpl extends NamedElementImpl implements org.smalluml.smalluml.String
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmallumlPackage.Literals.STRING;
  }

} //StringImpl
