/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.smalluml.smalluml.SmallumlPackage;
import org.smalluml.smalluml.SuperType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Super Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SuperTypeImpl extends MinimalEObjectImpl.Container implements SuperType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuperTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmallumlPackage.Literals.SUPER_TYPE;
  }

} //SuperTypeImpl
