/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smalluml.smalluml.Attribute#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends NamedElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(SuperType)
   * @see org.smalluml.smalluml.SmallumlPackage#getAttribute_Type()
   * @model
   * @generated
   */
  SuperType getType();

  /**
   * Sets the value of the '{@link org.smalluml.smalluml.Attribute#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(SuperType value);

} // Attribute
