/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getDate()
 * @model
 * @generated
 */
public interface Date extends NamedElement, SuperType
{
} // Date
