/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smalluml.smalluml.Enumeration#getSupertype <em>Supertype</em>}</li>
 * </ul>
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getEnumeration()
 * @model
 * @generated
 */
public interface Enumeration extends NamedElement
{
  /**
   * Returns the value of the '<em><b>Supertype</b></em>' containment reference list.
   * The list contents are of type {@link org.smalluml.smalluml.SuperType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Supertype</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Supertype</em>' containment reference list.
   * @see org.smalluml.smalluml.SmallumlPackage#getEnumeration_Supertype()
   * @model containment="true"
   * @generated
   */
  EList<SuperType> getSupertype();

} // Enumeration
