/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inheritance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smalluml.smalluml.Inheritance#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getInheritance()
 * @model
 * @generated
 */
public interface Inheritance extends EObject
{
  /**
   * Returns the value of the '<em><b>Children</b></em>' containment reference list.
   * The list contents are of type {@link org.smalluml.smalluml.Class}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Children</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' containment reference list.
   * @see org.smalluml.smalluml.SmallumlPackage#getInheritance_Children()
   * @model containment="true"
   * @generated
   */
  EList<org.smalluml.smalluml.Class> getChildren();

} // Inheritance
