/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getInteger()
 * @model
 * @generated
 */
public interface Integer extends SuperType
{
} // Integer
