/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smalluml.smalluml.Operation#isIsAbstract <em>Is Abstract</em>}</li>
 *   <li>{@link org.smalluml.smalluml.Operation#getReturnType <em>Return Type</em>}</li>
 *   <li>{@link org.smalluml.smalluml.Operation#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends NamedElement
{
  /**
   * Returns the value of the '<em><b>Is Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Abstract</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Abstract</em>' attribute.
   * @see #setIsAbstract(boolean)
   * @see org.smalluml.smalluml.SmallumlPackage#getOperation_IsAbstract()
   * @model
   * @generated
   */
  boolean isIsAbstract();

  /**
   * Sets the value of the '{@link org.smalluml.smalluml.Operation#isIsAbstract <em>Is Abstract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Abstract</em>' attribute.
   * @see #isIsAbstract()
   * @generated
   */
  void setIsAbstract(boolean value);

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' reference.
   * @see #setReturnType(SuperType)
   * @see org.smalluml.smalluml.SmallumlPackage#getOperation_ReturnType()
   * @model
   * @generated
   */
  SuperType getReturnType();

  /**
   * Sets the value of the '{@link org.smalluml.smalluml.Operation#getReturnType <em>Return Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(SuperType value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.smalluml.smalluml.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.smalluml.smalluml.SmallumlPackage#getOperation_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Operation
