/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.smalluml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Super Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.smalluml.smalluml.SmallumlPackage#getSuperType()
 * @model
 * @generated
 */
public interface SuperType extends EObject
{
} // SuperType
