/**
 * generated by Xtext 2.10.0
 */
package org.xtext.smalluml.validation;

import org.xtext.smalluml.validation.AbstractSmallUMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmallUMLValidator extends AbstractSmallUMLValidator {
}
