/**
 * generated by Xtext 2.10.0
 */
package org.smalluml.ui;

import org.smalluml.ui.AbstractSmallUMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class SmallUMLUiModule extends AbstractSmallUMLUiModule {
}
